### ISSUE TITLE
Preinscripción desde SMPorres.exe

### ISSUE THREAD

**Issue by lariaspaz** [lariaspaz/SMPorres#19]
* Preinscripción desde SMPorres.exe. 
* Seleccionando ciclo lectivo. 
* Nueva ventana.

**Comment by hernanjhc** [comment]
![imagen](https://user-images.githubusercontent.com/14355302/155625064-623c3e4a-d65c-49f3-a006-661620358d46.png)

Sugiero utilizar la misma ventana y permitir seleccionar una opcion entre ciclos lectivo actual y de preincripción.

**Comment by lariaspaz** [comment]
Si se van a inscribir un grupo de alumnos por vez, sí, está bien esa
opción. Sino, hay que hacer otra ventana adónde se lo pueda inscribir a 1
solo alumno.
Solamente se puede pre inscribir un alumno para el ciclo lectivo siguiente
al actualmente configurado globalmente.

**Comment by hernanjhc** [comment]
Se subio a rama "preinscripcion-desde-smporres.exe" asignar alumnos a cursos seleccionando ciclo lectivo actual o de preinscripcion. 
No entiendo muy bien lo siguiente: Solamente se puede pre inscribir un alumno para el ciclo lectivo siguiente
al actualmente configurado globalmente.

**Comment by leoariaspaz** [comment]
Sería el ciclo lectivo siguiente al de la tabla Configuración.
