### ISSUE TITLE
Vencimientos de cuotas incorrectos

### ISSUE THREAD

**Issue by lariaspaz** [lariaspaz/SMPorres#33]
Algunos planes de pago 2022 tienen cuotas con vencimiento 2021

**Comment by hernanjhc** [comment]
----> Script

select count(1)
from PlanesPago pp
inner join pagos p
on pp.id = p.IdPlanPago
where 
	pp.Estado = 1 and
	pp.CicloLectivo = 2022	and
	p.FechaVto >= '01/01/2021'	and
	p.FechaVto < '01/01/2023'
--2640

begin tran ciclolectivo2022

update pagos
set FechaVto = (
	select c.VtoCuota
	from Cuotas c
	where p.NroCuota = c.Cuota	and
	c.CicloLectivo = 2022
)
from PlanesPago pp
inner join pagos p
on pp.id = p.IdPlanPago
where 
	pp.Estado = 1 and
	pp.CicloLectivo = 2022	and
	p.FechaVto >= '01/01/2021'	and
	p.FechaVto < '01/01/2023'
--2640

--commit tran ciclolectivo2022
rollback tran ciclolectivo2022

**Comment by hernanjhc** [comment]
se corrio el script y versionó el mismo.
