### ISSUE TITLE
Devoluciones de matrículas

### ISSUE THREAD

**Issue by lariaspaz** [lariaspaz/SMPorres#34]
Devoluciones de matrículas 2022 cobradas con recargo.

**Comment by hernanjhc** [comment]
Hoy me contacté con Claudio Alaniz y le comenté sobre este tema, me informo que ellos van a manejar por fuera del sistema debido a que el mismo no está preparado. Por el momento no realizaron ningun tipo de acciones al respecto.

**Comment by leoariaspaz** [comment]
Si la tarea la van a solucionar por fuera del sistema y no tenemos que
modificar nada, se da por terminado este issue.

**Comment by hernanjhc** [comment]
Hoy se habló con Claudio, el excedente del pago de matricula se debera acreditar en el pago de la siguiente cuota. El sistema permitirá cargar manualmente el pago en efectivo y se deberá habilitar el campo de importe a pagar. Para que puedan registrar montos diferentes al calculado por el sistema.

**Comment by leoariaspaz** [comment]
No, ni en pedo haremos eso.
Ellos definen la necesidad, nosotros definimos cómo se la implementa en
nuestro sistema.
Para mí, hay que permitir cargar una bonificación de la cuota en moneda
Pesos en la ventana adónde se asienta un cobro manual. Esa bonificación se
debe grabar en una tabla extra, adónde se referencia al pago en cuestión y
adónde indique el monto de la bonificación, usuario que la hizo, fecha y
hora, y un posible motivo, como mínimo.
Si se te ocurre otra forma, bienvenida! Contarme y lo vamos viendo.
