### ISSUE TITLE
Datos de request en api de inscripción

### ISSUE THREAD

**Issue by lariaspaz** [lariaspaz/SMPorres#35]
La api recibe mal el nombre del alumno. Ver qué otros datos también se reciben mal.

**Comment by hernanjhc** [comment]
El nombre llega separado por puntos ejemplo " . nombre del alumno . ". No se controla la fecha de nacimiento, se cargan valores nulos del tipo 01/01/1990

**Comment by hernanjhc** [comment]
Se envió email al desarrollador del sistema de inscripcion del instituto informando la situación, se aguarda comentarios.
